# ===================================================================
# Spring Boot configuration for the "dev" profile.
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# spring config
# ===================================================================
spring:
#  redis:
#    port: 6397
#    database: 2
#    host: 127.0.0.1
#    password: passwd_redis

# ===================================================================
# druid config
# druid alibaba database connection pool
# ===================================================================
druid:
  url: jdbc:mysql://127.0.0.1:3306/xiao_mall_1.0.0?useUnicode=true&useSSL=false&characterEncoding=UTF-8
  username: root
  password: admin